from pprint import pprint
with open("website.html",  encoding="utf8") as file:
    #contents = file.read()
 alternatevly soup = BeautifulSoup(contents, "lxml")
soup = BeautifulSoup(contents, "html.parser")
 lxml and html.parser are the parsers for the html ( el mofasser)
print (soup.title.string)
print(soup)
print(soup.prettify())
print(soup.li)
all_anchor_tags = soup.find_all(name="a")
pprint(all_anchor_tags)
for tag in all_anchor_tags:
print(tag.getText())
print(tag.get("href"))
heading = soup.find(name="h1", id='name')
print(heading)
section_heading = soup.find(name ="h3", class_="heading")
print(section_heading)
print(section_heading.name)
print(section_heading.text)
print(section_heading.get("class"))
company_url = soup.select_one(selector="p a")
name = soup.select_one("#name")
print (company_url)
print(name)
headings = soup.select(".heading")
pprint(headings)